[package]
name = "updater"
version = "1.1.3"
edition = "2024"
authors = ["Paijo"]
description = "Software Update for ABS & Complement"
build = "build.rs"

[build-dependencies]
winresource = "0.1"

[package.metadata.winresource]
FileDescription = "Software Update for ABS & Complement"
LegalCopyright = "By Paijo"
OriginalFilename = "updater.exe"
CompanyName = "Paijo"

[dependencies]
runtime = { path = "../runtime", features = ["upgrade"] }
tokio = { version = "1", features = ["full"] }
indicatif = "0.17"
futures-util = "0.3"
once_cell = "1.21"
sevenz-rust2 = "0.13"

[target.'cfg(windows)'.dependencies]
zip = "3"
windows-version = "0.1.1"

[target.'cfg(unix)'.dependencies]
tar = "0.4"
flate2 = "1.0"